ALTER TABLE "Event"
ADD COLUMN IF NOT EXISTS "disputeAsked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "disputeConfirmedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "disputeResult" BOOLEAN;
