ALTER TYPE "InvitationStatus" ADD VALUE IF NOT EXISTS 'RESERVED';

ALTER TABLE "Invitation" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);

ALTER TABLE "Invitation" ALTER COLUMN "guestFirstName" DROP NOT NULL;
ALTER TABLE "Invitation" ALTER COLUMN "guestLastName" DROP NOT NULL;
